# Generated by Django 3.2.13 on 2022-04-29 12:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('instagram', '0005_post_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='post',
            field=models.ForeignKey(limit_choices_to={'is_public': False}, on_delete=django.db.models.deletion.CASCADE, to='instagram.post'),
        ),
    ]
